# Generated by Django 4.2.4 on 2024-05-21 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_comment_commentid_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
        migrations.RemoveField(
            model_name='postreactions',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postreactions',
            name='post',
        ),
        migrations.DeleteModel(
            name='CommentReactions',
        ),
        migrations.DeleteModel(
            name='PostReactions',
        ),
    ]
