# Generated by Django 4.2.4 on 2024-05-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_reactions_remove_postreactions_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactions',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reactions',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reactions',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reactions',
        ),
    ]
